global:
  name: orakl-grafana-as-code
  namespace: orakl

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240308.0151.22ae7e7"
  imagePullPolicy: IfNotPresent
  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
  imagePullSecrets:
    - name: gar-json-key

deployment:
  name: orakl-grafana-as-code
  replicas: 1
  env:
    - name: CYPRESS_DELEGATOR_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: CYPRESS_DELEGATOR_DB_PW
    - name: CYPRESS_GRAPHNODE_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: CYPRESS_GRAPHNODE_DB_PW
    - name: CYPRESS_MAIN_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: CYPRESS_MAIN_DB_PW
    - name: CYPRESS_MONITOR_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: CYPRESS_MONITOR_DB_PW
    - name: NETWORK
      value: "cypress"
