global:
  name: orakl-grafana-as-code
  namespace: orakl

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240509.0931.65ffee5"

  imagePullSecrets:
    - name: gar-json-key

annotations: 
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'orakl'
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "baobab/data/grafana" -}}
      #!/bin/bash
      export BAOBAB_DELEGATOR_DB_PW="{{ .Data.data.BAOBAB_DELEGATOR_DB_PW }}"
      export BAOBAB_GRAPHNODE_DB_PW="{{ .Data.data.BAOBAB_GRAPHNODE_DB_PW }}"
      export BAOBAB_MAIN_DB_PW="{{ .Data.data.BAOBAB_MAIN_DB_PW }}"
      export BAOBAB_MONITOR_DB_PW="{{ .Data.data.BAOBAB_MONITOR_DB_PW }}"
    {{- end }}  

deployment:
  name: orakl-grafana-as-code
  replicas: 1
  env:
    - name: NETWORK
      value: "baobab"
    - name: VAULT_ADDR
      value: http://vault.vault.svc.cluster.local:8200/
    - name: JWT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 4Gi