global:
  name: grafana-as-code
  namespace: orakl

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240423.0114.270d993"
  imagePullPolicy: IfNotPresent
  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
  imagePullSecrets:
    - name: gar-json-key

deployment:
  name: orakl-grafana-as-code
  replicas: 1
