global:
  name: orakl-grafana-as-code
  namespace: orakl-cypress

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240517.0920.aa3cf01"

  imagePullSecrets:
    - name: gar-json-key

annotations: 
  vault.hashicorp.com/auth-path: "auth/monitor"
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'monitor'
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "monitor/data/grafana-cypress" -}}
      #!/bin/bash
      export CYPRESS_DELEGATOR_DB_PW="{{ .Data.data.CYPRESS_DELEGATOR_DB_PW }}"
      export CYPRESS_GRAPHNODE_DB_PW="{{ .Data.data.CYPRESS_GRAPHNODE_DB_PW }}"
      export CYPRESS_MAIN_DB_PW="{{ .Data.data.CYPRESS_MAIN_DB_PW }}"
      export CYPRESS_MONITOR_DB_PW="{{ .Data.data.CYPRESS_MONITOR_DB_PW }}"
    {{- end }}  

deployment:
  name: orakl-grafana-as-code
  replicas: 1
  env:
    - name: NETWORK
      value: "cypress"

  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 2000m
      memory: 2Gi