global:
  name: grafana-as-code
  namespace: orakl

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240229.0613.748eb76"
  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
  imagePullSecrets:
    - name: gar-json-key

deployment:
  name: orakl-grafana-as-code
  replicas: 1
  env:
    - name: BAOBAB_DELEGATOR_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: BAOBAB_DELEGATOR_DB_PW
    - name: BAOBAB_GRAPHNODE_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: BAOBAB_GRAPHNODE_DB_PW
    - name: BAOBAB_MAIN_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: BAOBAB_MAIN_DB_PW
    - name: BAOBAB_MONITOR_DB_PW
      valueFrom:
        secretKeyRef:
          name: grafana-as-code-secrets
          key: BAOBAB_MONITOR_DB_PW
    - name: NETWORK
      value: "baobab"
