global:
  name: orakl-grafana-as-code
  namespace: orakl-baobab

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana #repository url
  pullPolicy: IfNotPresent
  tag: "monitor.v1.0.0.20240625.0104.b05ec0f"

  imagePullSecrets:
    - name: gar-json-key

annotations:
  vault.hashicorp.com/auth-path: "auth/monitor"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "monitor"
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "monitor/data/grafana-baobab" -}}
      #!/bin/bash
      export BAOBAB_DELEGATOR_DB_PW="{{ .Data.data.BAOBAB_DELEGATOR_DB_PW }}"
      export BAOBAB_GRAPHNODE_DB_PW="{{ .Data.data.BAOBAB_GRAPHNODE_DB_PW }}"
      export BAOBAB_MAIN_DB_PW="{{ .Data.data.BAOBAB_MAIN_DB_PW }}"
      export BAOBAB_MONITOR_DB_PW="{{ .Data.data.BAOBAB_MONITOR_DB_PW }}"
    {{- end }}

deployment:
  name: orakl-grafana-as-code
  replicas: 1
  env:
    - name: NETWORK
      value: "baobab"
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 2000m
      memory: 2Gi
