global:
  name: orakl-grafana-as-code
  namespace: orakl

image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-grafana
  pullPolicy: IfNotPresent
  tag: "latest"
  imagePullSecrets:
    - name: gar-json-key

job:
  name: orakl-grafana-as-code
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  env: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
