## Klaytn Orakl Api Configuration
## created by Bisonai
global:
  image:
    repository: public.ecr.aws/bisonai/orakl-goapi
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20240205.0346.c0a6c84"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

api:
  enabled: true
  replicas: 1
  podSecurityContext: {}

  containerSecurityContext: {}

  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi

nodeSelector: {}
tolerations: []
dotenv: {}

deployment:
  name: orakl-goapi
  replicas: 1
