jobs:
  ###
  # Backup Orakl DB
  ###
  orakl-db-backup:
    image:
      repository: debian
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "0 */6 * * *"
    failedJobHistoryLimit: 3
    successfulJobHistoryLimit: 10
    concurrencyPolicy: Allow
    restartPolicy: Never 
    ttlSecondsAfterFinished: 30
    serviceAccount:
      annotations:
        iam.gke.io/gcp-serviceaccount: "orakl-db-backup@orakl-cypress-prod.iam.gserviceaccount.com"
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        echo "Step 1: Install dependencies"
        apt -y update && apt -y install postgresql-client

        echo "Step 2: Export old data to csv files"
        psql $DATABASE_URL -t -c "SELECT tablename FROM pg_tables WHERE tablename LIKE 'data_%';" \
        | xargs -I {} psql $DATABASE_URL -c "\copy {} to './{}.csv' WITH DELIMITER ',' CSV HEADER;"

        echo "Step 3: Upload all csv files to GCS bucket."
        ls | grep 'csv'
        ls | grep 'csv' | awk '{print $1}' | xargs -I {} gcloud storage cp {} gs://orakl-db-backup-cypress

        echo "Step 4: Delete old data tables"
        psql $DATABASE_URL -t -c "SELECT tablename FROM pg_tables WHERE tablename LIKE 'data_%';"
    env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: api-secrets
            key: DATABASE_URL
