jobs:
  ###
  # Renew TLS certificate for `*.orakl.network` domain
  ###
  orakl-tls-renew:
    image:
      repository: debian
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "0 0 1 */2 *"
    failedJobHistoryLimit: 3
    successfulJobHistoryLimit: 10
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 30
    volumes:
      - name: orakl-tls-renew-volume
        gcePersistentDisk:
          pdName: orakl-tls-renew-disk
          fsType: ext4
    volumeMounts:
      - name: orakl-tls-renew-volume
        mountPath: /etc/letsencrypt
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        apt -y update && apt -y install curl
        curl https://getcroc.schollz.com | bash
    stdin: true
    tty: true
