jobs:
  ###
  # Renew TLS certificate for `*.orakl.network` domain
  ###
  orakl-tls-renew:
    image:
      repository: debian
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "0 0 1 */2 *"
    failedJobHistoryLimit: 3
    successfulJobHistoryLimit: 10
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 30
    volumes:
      - name: orakl-tls-renew-volume
        gcePersistentDisk:
          pdName: orakl-tls-renew-disk
          fsType: ext4
    volumeMounts:
      - name: orakl-tls-renew-volume
        mountPath: /etc/letsencrypt
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        apt -y update && apt -y install python3 python3-pip python3-venv
        python3 -m venv /certbot && /certbot/bin/pip3 install -U certbot-dns-godaddy
        /certbot/bin/certbot renew \
        --authenticator dns-godaddy \
        --dns-godaddy-credentials ./credentials.ini \
        --dns-godaddy-propagation-seconds 900 \
        --keep-until-expiring --non-interactive --expand \
        --server https://acme-v02.api.letsencrypt.org/directory
        sleep infinity
