apiVersion: apps/v1
kind: Deployment
metadata:
  name: orakl-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orakl-cron
  template:
    metadata:
      labels:
        app: orakl-cron
    spec:
      containers:
        - name: orakl-cron
          image: public.ecr.aws/u6t6w0e4/orakl-general:cron.20230630.0617.08f9bdd
          volumeMounts:
            - name: orakl-vrf-listener-storage
              mountPath: /app/vrf-listener
            - name: orakl-vrf-worker-storage
              mountPath: /app/vrf-worker
            - name: orakl-vrf-reporter-storage
              mountPath: /app/vrf-reporter     
            - name: orakl-request-response-listener-storage
              mountPath: /app/request-response-listener
            - name: orakl-request-response-worker-storage
              mountPath: /app/request-response-worker
            - name: orakl-request-response-reporter-storage
              mountPath: /app/request-response-reporter            
            - name: orakl-aggregator-listener-storage
              mountPath: /app/aggregator-listener
            - name: orakl-aggregator-worker-storage
              mountPath: /app/aggregator-worker
            - name: orakl-aggregator-reporter-storage                                            
              mountPath: /app/aggregator-reporter
      volumes:
        - name: orakl-vrf-listener-storage
          persistentVolumeClaim:
            claimName: orakl-vrf-listener-pvc
        - name: orakl-vrf-worker-storage
          persistentVolumeClaim:
            claimName: orakl-vrf-worker-pvc
        - name: orakl-vrf-reporter-storage
          persistentVolumeClaim:
            claimName: orakl-vrf-reporter-pvc            
        - name: orakl-request-response-listener-storage
          persistentVolumeClaim:
            claimName: orakl-request-response-listener-pvc
        - name: orakl-request-response-worker-storage
          persistentVolumeClaim:
            claimName: orakl-request-response-worker-pvc
        - name: orakl-request-response-reporter-storage
          persistentVolumeClaim:
            claimName: orakl-request-response-reporter-pvc                 
        - name: orakl-aggregator-listener-storage
          persistentVolumeClaim:
            claimName: orakl-aggregator-listener-pvc
        - name: orakl-aggregator-worker-storage
          persistentVolumeClaim:
            claimName: orakl-aggregator-worker-pvc
        - name: orakl-aggregator-reporter-storage
          persistentVolumeClaim:
            claimName: orakl-aggregator-reporter-pvc                 