apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bisontry-daily-report-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: COMPANY
      remoteRef:
        key: baobab/bisontry-daily-report
        property: COMPANY
    - secretKey: OPERATOR
      remoteRef:
        key: baobab/bisontry-daily-report
        property: OPERATOR
    - secretKey: SYSTEM
      remoteRef:
        key: baobab/bisontry-daily-report
        property: SYSTEM
    - secretKey: NODE_ENV
      remoteRef:
        key: baobab/bisontry-daily-report
        property: NODE_ENV
    - secretKey: NETWORK
      remoteRef:
        key: baobab/bisontry-daily-report
        property: NETWORK
    - secretKey: MESSENGER_ENDPOINT
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MESSENGER_ENDPOINT
    - secretKey: MONITOR_POSTGRES_USER
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MONITOR_POSTGRES_USER
    - secretKey: MONITOR_POSTGRES_HOST
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MONITOR_POSTGRES_HOST
    - secretKey: MONITOR_POSTGRES_DATABASE
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MONITOR_POSTGRES_DATABASE
    - secretKey: MONITOR_POSTGRES_PASSWORD
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MONITOR_POSTGRES_PASSWORD
    - secretKey: MONITOR_POSTGRES_PORT
      remoteRef:
        key: baobab/bisontry-daily-report
        property: MONITOR_POSTGRES_PORT
    - secretKey: GRAPHNODE_POSTGRES_USER
      remoteRef:
        key: baobab/bisontry-daily-report
        property: GRAPHNODE_POSTGRES_USER
    - secretKey: GRAPHNODE_POSTGRES_HOST
      remoteRef:
        key: baobab/bisontry-daily-report
        property: GRAPHNODE_POSTGRES_HOST
    - secretKey: GRAPHNODE_POSTGRES_DATABASE
      remoteRef:
        key: baobab/bisontry-daily-report
        property: GRAPHNODE_POSTGRES_DATABASE
    - secretKey: GRAPHNODE_POSTGRES_PASSWORD
      remoteRef:
        key: baobab/bisontry-daily-report
        property: GRAPHNODE_POSTGRES_PASSWORD
    - secretKey: GRAPHNODE_POSTGRES_PORT
      remoteRef:
        key: baobab/bisontry-daily-report
        property: GRAPHNODE_POSTGRES_PORT
    - secretKey: PROVIDER
      remoteRef:
        key: baobab/bisontry-daily-report
        property: PROVIDER
