apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boot-api-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: baobab/boot-api
        property: DATABASE_URL
    - secretKey: PRIVATE_NETWORK_SECRET
      remoteRef:
        key: baobab/boot-api
        property: PRIVATE_NETWORK_SECRET
