apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: baobab/node
        property: DATABASE_URL
    - secretKey: KLAYTN_REPORTER_PK
      remoteRef:
        key: baobab/node
        property: KLAYTN_REPORTER_PK
    - secretKey: PRIVATE_NETWORK_SECRET
      remoteRef:
        key: baobab/node
        property: PRIVATE_NETWORK_SECRET
