apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: request-response-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: CHAIN
      remoteRef:
        key: baobab/request-response
        property: CHAIN
    - secretKey: NODE_ENV
      remoteRef:
        key: baobab/request-response
        property: NODE_ENV
    - secretKey: LOG_LEVEL
      remoteRef:
        key: baobab/request-response
        property: LOG_LEVEL
    - secretKey: ORAKL_NETWORK_API_URL
      remoteRef:
        key: baobab/request-response
        property: ORAKL_NETWORK_API_URL
    - secretKey: PROVIDER_URL
      remoteRef:
        key: baobab/request-response
        property: PROVIDER_URL
    - secretKey: REDIS_HOST
      remoteRef:
        key: baobab/request-response
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: baobab/request-response
        property: REDIS_PORT
