apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-reporter
  labels: 
    {{- include "orakl-vrf.labels.reporter" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: 6000
    targetPort: 6000
    protocol: TCP
  - name: healthcheck
    port: 8080
    targetPort: 8080
  selector:
    {{- include "orakl-vrf.selectorLabels.reporter" . | nindent 6 }}
