{{- range $jobname, $job := .Values.jobs }}
{{- if hasKey $job "clusterRole" }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if and (hasKey $job "clusterRole") (hasKey $job "clusterRole.name") }}
  name: {{ $job.clusterRole.name | default (print $.Release.Name "-" $jobname) }}
  {{- end }}
  namespace: {{ default $.Release.Namespace $job.namespace }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
    cron: {{ $jobname }}
  {{- if and (hasKey $job "clusterRole") (hasKey $job "clusterRole.annotations") }}
  {{- with $job.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
rules:
  {{ toYaml $job.rules }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- if and (hasKey $job "clusterRole") (hasKey $job "clusterRole.name") }}
  name: {{ $job.clusterRole.name | default (print $.Release.Name "-" $jobname "-binding") }}
  {{- else }}
  name: {{ $.Release.Name }}-{{ $jobname }}
  {{- end }}
subjects:
- kind: ServiceAccount
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.name") }}
  name: {{ $job.serviceAccount.name }}
  {{- else }}
  name: {{ $.Release.Name}}-{{ $jobname }}
  {{- end }}
  namespace: {{ default $.Release.Namespace $job.namespace }}
roleRef:
  kind: ClusterRole
  {{- if and (hasKey $job "clusterRole") (hasKey $job "clusterRole.name") }}
  name: {{ $job.clusterRole.name | default (print $.Release.Name "-" $jobname) }}
  {{- else }}
  name: {{ $.Release.Name }}-{{ $jobname }}
  {{- end }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}

