apiVersion: apps/v1
kind: Deployment
metadata:
  name: delegator
  labels:
    {{- include "orakl-delegator.labels.delegator" . | nindent 4 }}
spec:
  replicas: {{ .Values.delegator.replicas }}
  selector:
    matchLabels:
      {{- include "orakl-delegator.selectorLabels.delegator" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orakl-delegator.selectorLabels.delegator" . | nindent 8 }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.delegator.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.delegator.podSecurityContext | nindent 8 }}
      {{- if .Values.global.affinity.enabled }}        
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.global.affinity.key }}
                operator: In
                values:
                - {{ .Values.global.affinity.value }}
      {{- end }}  
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.delegator.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.global.secretManager.enabled }}
          env:
            - name: DATABASE_URL          
              valueFrom:
                secretKeyRef:
                  name: orakl-delegator-secrets
                  key: DATABASE_URL
            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-delegator-secrets
                  key: APP_PORT
            - name: PROVIDER_URL
              value: "{{ .Values.global.config.PROVIDER_URL }}"
              valueFrom:
                secretKeyRef:
                  name: orakl-delegator-secrets
                  key: PROVIDER_URL
          {{ else }}
          envFrom:
            - configMapRef:
                name: orakl-delegator-configmap
          {{ end }}

          command: ["yarn"]
          args: ["start:prod"]
          ports:
          - name: http
            containerPort: {{ .Values.global.config.APP_PORT | default 5050 | int  }}
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.global.livenessProbe.path }}
              port: {{ .Values.global.config.APP_PORT | default 5050 | int  }}
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.global.readinessProbe.path }}
              port: {{ .Values.global.config.APP_PORT | default 5050 | int  }}
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}              
          {{- end }}          
          resources:
            {{- toYaml .Values.delegator.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
