apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    app.kubernetes.io/name: {{ .Values.deployment.name }}
    app.kubernetes.io/instance: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.delegator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      app.kubernetes.io/name: {{ .Values.deployment.name }}
      app.kubernetes.io/instance: {{ .Values.deployment.name }}
  template:
    metadata:
      {{- with .Values.delegator.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.deployment.name }}
        app.kubernetes.io/name: {{ .Values.deployment.name }}
        app.kubernetes.io/instance: {{ .Values.deployment.name }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.delegator.podSecurityContext | nindent 8 }}
      {{- if .Values.global.affinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.global.affinity.key }}
                operator: In
                values:
                - {{ .Values.global.affinity.value }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.delegator.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/bin/sh","-c"]
          args: [". /vault/secrets/config && ./start-go.sh delegatorbin"]
          env:
          {{- if .Values.global.secretManager.enabled }}
            {{- toYaml .Values.global.googleSecretManager.env | nindent 12 }}
          {{ else }}  
            {{- toYaml .Values.delegator.env | nindent 12 }}
          {{ end }}
            - name: APP_PORT
              value: "5050"          
          ports:
          - name: http
            containerPort: 5050
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.global.livenessProbe.path }}
              port: 5050
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.global.readinessProbe.path }}
              port: 5050
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.delegator.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}