{{- if .Values.delegator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.delegator.serviceAccount.name }}
  labels:
    {{- include "orakl-delegator.labels.delegator" . | nindent 4 }}
  {{- with .Values.delegator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.delegator.loadBalancerIP }}"
{{- end }}
