{{- if .Values.global.secretManager.enabled }}
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-delegator-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.global.secretManager.secretId }}
      versionId: {{ .Values.global.secretManager.versionId }}
{{- end}}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLmtZUGdCU0w1ODRZWGtqWWVxbjZXQjBSNA==

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: delegator-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: baobab/prod/delegator
      property: DATABASE_URL
  - secretKey: APP_PORT
    remoteRef:
      key: baobab/prod/delegator
      property: APP_PORT
  - secretKey: PROVIDER_URL
    remoteRef:
      key: baobab/prod/delegator
      property: PROVIDER_URL

