apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}

