apiVersion: v1
kind: Service
metadata:
  name: orakl-delegator
spec:
  # type: ClusterIP
  ports:
  # - port: {{ .Values.global.config.APP_PORT | default 5050 | int  }}
  - port: 5050
    targetPort: http
    protocol: TCP
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: "{{ .Values.delegator.loadBalancerIP }}" 
  selector:
    {{- include "orakl-delegator.selectorLabels.delegator" . | nindent 4 }} 
