apiVersion: v1
kind: Service
metadata:
  name: orakl-delegator
spec:
  # type: ClusterIP
  ports:
  - port: 5050
    targetPort: http
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 34.126.65.247
  selector:
    {{- include "orakl-delegator.selectorLabels.delegator" . | nindent 4 }} 
