apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: baobab/prod/api
      property: DATABASE_URL
  - secretKey: ENCRYPT_PASSWORD
    remoteRef:
      key: baobab/prod/api
      property: ENCRYPT_PASSWORD