apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bisontry-event-checker-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: COMPANY
      remoteRef:
        key: baobab/bisontry-event-checker
        property: COMPANY
    - secretKey: OPERATOR
      remoteRef:
        key: baobab/bisontry-event-checker
        property: OPERATOR
    - secretKey: SYSTEM
      remoteRef:
        key: baobab/bisontry-event-checker
        property: SYSTEM
    - secretKey: NODE_ENV
      remoteRef:
        key: baobab/bisontry-event-checker
        property: NODE_ENV
    - secretKey: NETWORK
      remoteRef:
        key: baobab/bisontry-event-checker
        property: NETWORK
    - secretKey: PROVIDER1
      remoteRef:
        key: baobab/bisontry-event-checker
        property: PROVIDER1
    - secretKey: PROVIDER2
      remoteRef:
        key: baobab/bisontry-event-checker
        property: PROVIDER2
    - secretKey: PROVIDER3
      remoteRef:
        key: baobab/bisontry-event-checker
        property: PROVIDER3
    - secretKey: CONFIG_CRON_PERIOD
      remoteRef:
        key: baobab/bisontry-event-checker
        property: CONFIG_CRON_PERIOD
    - secretKey: CONFIG_EVENT_PERIOD
      remoteRef:
        key: baobab/bisontry-event-checker
        property: CONFIG_EVENT_PERIOD
    - secretKey: MESSENGER_ENDPOINT
      remoteRef:
        key: baobab/bisontry-event-checker
        property: MESSENGER_ENDPOINT