apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: delegator-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: baobab/prod/delegator
      property: DATABASE_URL
  - secretKey: EXTERNAL_IP
    remoteRef:
      key: baobab/prod/delegator
      property: EXTERNAL_IP
  - secretKey: PROVIDER_URL
    remoteRef:
      key: baobab/prod/delegator
      property: PROVIDER_URL      