apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: por-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: baobab/por
        property: DATABASE_URL
