kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tome-role-binding
  namespace: orakl
subjects:
- kind: User
  name: kelvin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: member-role
  apiGroup: rbac.authorization.k8s.io
