kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: orakl
  name: member-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
