{{- if .Values.listener.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.listener.serviceAccount.name }}
  labels:
    {{- include "orakl-aggregator.labels.listener" . | nindent 4 }}
  {{- with .Values.listener.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
