apiVersion: v1
kind: Service
metadata:
  name: aggregator-listener
  labels: 
    {{- include "orakl-aggregator.labels.listener" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.listener" . | nindent 6 }}
