apiVersion: v1
kind: Service
metadata:
  name: orakl-aggregator-listener
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.listener" . | nindent 6 }}

