apiVersion: v1
kind: Service
metadata:
  name: aggregator-listener
  labels: 
    {{- include "orakl-aggregator.labels.listener" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.listener" . | nindent 6 }}
