apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-listener
  labels: 
    {{- include "orakl-aggregator.labels.listener" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: 4000
    targetPort: 4000
    protocol: TCP
  - name: healthcheck
    port: 8080 
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.listener" . | nindent 6 }}
