apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.persistentVolume.log.name | default "orakl-log" }}-pv"
spec:
  capacity:
    storage: "{{ .Values.persistentVolume.log.size }}"
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: orakl-log-baobab
    fsType: ext4
  storageClassName: orakl-sc    