apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name | default "orakl-log" }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.config.size }}"
  volumeName:  "{{ .Values.config.name | default "orakl-log" }}-pv"

  storageClassName: orakl-sc