apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.name | default "orakl-log" }}-pv"
spec:
  capacity:
    storage: "{{ .Values.config.size }}"
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: "{{ .Values.config.pdName }}"
    fsType: ext4
  storageClassName: orakl-sc    