apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: orakl-monitor-api
  template:
    metadata:
      labels:
        app: orakl-monitor-api
    spec:
      containers:
        - name: orakl-monitor-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:

            - name: PROVIDER
            {{- if .Values.config.PROVIDER }}
              value: {{ .Values.config.PROVIDER }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: BAOBAB_EN_NODE
            {{ end }}

            - name: MONITOR_POSTGRES_USER
            {{- if .Values.config.MONITOR_POSTGRES_USER }}
              value: {{ .Values.config.MONITOR_POSTGRES_USER }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: MONITOR_POSTGRES_USER
            {{ end }}

            - name: MONITOR_POSTGRES_PASSWORD
            {{- if .Values.config.MONITOR_POSTGRES_PASSWORD }}
              value: {{ .Values.config.MONITOR_POSTGRES_PASSWORD }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: MONITOR_POSTGRES_PASSWORD
            {{ end }}

            - name: MONITOR_POSTGRES_HOST
            {{- if .Values.config.MONITOR_POSTGRES_HOST }}
              value: {{ .Values.config.MONITOR_POSTGRES_HOST }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: MONITOR_POSTGRES_HOST
            {{ end }}

            - name: MONITOR_POSTGRES_PORT
            {{- if .Values.config.MONITOR_POSTGRES_PORT }}
              value: {{ .Values.config.MONITOR_POSTGRES_PORT }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: MONITOR_POSTGRES_PORT
            {{ end }}

            - name: MONITOR_POSTGRES_DATABASE
            {{- if .Values.config.MONITOR_POSTGRES_DATABASE }}
              value: {{ .Values.config.MONITOR_POSTGRES_DATABASE }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: MONITOR_POSTGRES_DATABASE
            {{ end }}

            - name: ORAKL_POSTGRES_USER
            {{- if .Values.config.ORAKL_POSTGRES_USER }}
              value: {{ .Values.config.ORAKL_POSTGRES_USER }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: ORAKL_POSTGRES_USER
            {{ end }}

            - name: ORAKL_POSTGRES_PASSWORD
            {{- if .Values.config.ORAKL_POSTGRES_PASSWORD }}
              value: {{ .Values.config.ORAKL_POSTGRES_PASSWORD }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: ORAKL_POSTGRES_PASSWORD
            {{ end }}

            - name: ORAKL_POSTGRES_HOST
            {{- if .Values.config.ORAKL_POSTGRES_HOST }}
              value: {{ .Values.config.ORAKL_POSTGRES_HOST }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: ORAKL_POSTGRES_HOST
            {{ end }}

            - name: ORAKL_POSTGRES_PORT
            {{- if .Values.config.ORAKL_POSTGRES_PORT }}
              value: {{ .Values.config.ORAKL_POSTGRES_PORT }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: ORAKL_POSTGRES_PORT
            {{ end }}

            - name: ORAKL_POSTGRES_DATABASE
            {{- if .Values.config.ORAKL_POSTGRES_DATABASE }}
              value: {{ .Values.config.ORAKL_POSTGRES_DATABASE }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: ORAKL_POSTGRES_DATABASE
            {{ end }}

            - name: GRAPH_NODE_POSTGRES_USER
            {{- if .Values.config.GRAPH_NODE_POSTGRES_USER }}
              value: {{ .Values.config.GRAPH_NODE_POSTGRES_USER }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: GRAPH_NODE_POSTGRES_USER
            {{ end }}

            - name: GRAPH_NODE_POSTGRES_PASSWORD
            {{- if .Values.config.GRAPH_NODE_POSTGRES_PASSWORD }}
              value: {{ .Values.config.GRAPH_NODE_POSTGRES_PASSWORD }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: GRAPH_NODE_POSTGRES_PASSWORD
            {{ end }}

            - name: GRAPH_NODE_POSTGRES_HOST
            {{- if .Values.config.GRAPH_NODE_POSTGRES_HOST }}
              value: {{ .Values.config.GRAPH_NODE_POSTGRES_HOST }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: GRAPH_NODE_POSTGRES_HOST
            {{ end }}

            - name: GRAPH_NODE_POSTGRES_PORT
            {{- if .Values.config.GRAPH_NODE_POSTGRES_PORT }}
              value: {{ .Values.config.GRAPH_NODE_POSTGRES_PORT }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: GRAPH_NODE_POSTGRES_PORT
            {{ end }}

            - name: GRAPH_NODE_POSTGRES_DATABASE
            {{- if .Values.config.GRAPH_NODE_POSTGRES_DATABASE }}
              value: {{ .Values.config.GRAPH_NODE_POSTGRES_DATABASE }}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: orakl-monitor-secrets
                  key: GRAPH_NODE_POSTGRES_DATABASE
            {{ end }}

          command:
            - yarn
            - start:prod
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
