apiVersion: v1
kind: Service
metadata:
  name: orakl-monitor-api
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app.kubernetes.io/name: orakl-monitor-api
