{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
