apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
          - name: grafana
            containerPort: 3000
          env:
            - name: BAOBAB_DELEGATOR_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: BAOBAB_DELEGATOR_DB_PW
            - name: BAOBAB_GRAPHNODE_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: BAOBAB_GRAPHNODE_DB_PW
            - name: BAOBAB_MAIN_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: BAOBAB_MAIN_DB_PW
            - name: BAOBAB_MONITOR_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: BAOBAB_MONITOR_DB_PW
            - name: NETWORK
              value: "baobab"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"


            - name: CYPRESS_DELEGATOR_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: CYPRESS_DELEGATOR_DB_PW
            - name: CYPRESS_GRAPHNODE_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: CYPRESS_GRAPHNODE_DB_PW
            - name: CYPRESS_MAIN_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: CYPRESS_MAIN_DB_PW
            - name: CYPRESS_MONITOR_DB_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-as-code-secrets
                  key: CYPRESS_MONITOR_DB_PW
            - name: NETWORK
              value: "cypress"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
