apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: [". /vault/secrets/config && /usr/local/bin/orakl-grafana-entrypoint.sh"]          
          ports:
          - name: grafana
            containerPort: 3000
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}