apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}-{{ .Release.Revision }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit | default 3 }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished | default 300 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.job.name }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: dashboard-uploader
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - ". /vault/secrets/config && /usr/local/bin/grafana-api-uploader.sh"
          env:
            {{- toYaml .Values.job.env | nindent 12 }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
