apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - name: grafana
      protocol: TCP
      port: 80
      targetPort: 3000
