apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-worker
  labels:
    {{- include "orakl-aggregator.labels.worker" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "orakl-aggregator.selectorLabels.worker" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orakl-aggregator.selectorLabels.worker" . | nindent 8 }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.worker.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      {{- if .Values.global.affinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.global.affinity.key }}
                operator: In
                values:
                - {{ .Values.global.affinity.value }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.global.secretManager.enabled }}
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: NODE_ENV
            - name: ORAKL_NETWORK_API_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: ORAKL_NETWORK_API_URL
            - name: ORAKL_NETWORK_DELEGATOR_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: ORAKL_NETWORK_DELEGATOR_URL
            - name: CHAIN
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: CHAIN
            - name: HEALTH_CHECK_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: HEALTH_CHECK_PORT
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: SLACK_WEBHOOK_URL
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: LOG_LEVEL
            - name: LOG_DIR
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: LOG_DIR
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: REDIS_PORT
            - name: PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-aggregator-secrets
                  key: PROVIDER_URL
            - name: WORKER_PORT
              value: {{ .Values.worker.APP_PORT | default 5000 | int  }}
          {{ else }}
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: NODE_ENV
            - name: ORAKL_NETWORK_API_URL
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: ORAKL_NETWORK_API_URL
            - name: ORAKL_NETWORK_DELEGATOR_URL
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: ORAKL_NETWORK_DELEGATOR_URL
            - name: CHAIN
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: CHAIN
            - name: LOG_LEVEL
              value: "info"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: REDIS_PORT
            - name: PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: aggregator-secrets
                  key: PROVIDER_URL
            - name: WORKER_PORT
              value: "5000"
            - name: HEALTH_CHECK_PORT
              value: "8080"
          {{ end }}
          command: ["yarn"]
          args: [start:worker:data_feed]
          ports:
          - name: watchman
            containerPort: 5000
          - name: healthcheck
            containerPort: 8080
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
