apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-worker
  labels: 
    {{- include "orakl-aggregator.labels.worker" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: healthcheck
    port: 8080 
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.worker" . | nindent 6 }}
