apiVersion: v1
kind: Service
metadata:
  name: aggregator-worker
  labels: 
    {{- include "orakl-aggregator.labels.worker" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.worker" . | nindent 6 }}
