apiVersion: v1
kind: ConfigMap
metadata:
  name: orakl-cli-configmap
data:
  ORAKL_NETWORK_API_URL: "{{ .Values.global.config.ORAKL_NETWORK_API_URL }}"
  ORAKL_NETWORK_FETCHER_URL: "{{ .Values.global.config.ORAKL_NETWORK_FETCHER_URL }}"
  ORAKL_NETWORK_DELEGATOR_URL: "{{ .Values.global.config.ORAKL_NETWORK_DELEGATOR_URL }}"
  LISTENER_SERVICE_HOST: "{{ .Values.global.config.LISTENER_SERVICE_HOST }}"
  LISTENER_SERVICE_PORT: "{{ .Values.global.config.LISTENER_SERVICE_PORT }}"
  WORKER_SERVICE_HOST: "{{ .Values.global.config.WORKER_SERVICE_HOST }}"
  WORKER_SERVICE_PORT: "{{ .Values.global.config.WORKER_SERVICE_PORT }}"
  REPORTER_SERVICE_HOST: "{{ .Values.global.config.REPORTER_SERVICE_HOST }}"
  REPORTER_SERVICE_PORT: "{{ .Values.global.config.REPORTER_SERVICE_PORT }}"
  