apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  labels:
    {{- include "orakl-cli.labels.cli" . | nindent 4 }}
spec:
  replicas: {{ .Values.cli.replicas }}
  selector:
    matchLabels:
      {{- include "orakl-cli.selectorLabels.cli" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orakl-cli.selectorLabels.cli" . | nindent 8 }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.cli.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.cli.podSecurityContext | nindent 8 }}
      volumes:
      {{ if .Values.global.hostPath.enable }}
        # {{- toYaml .Values.global.hostPath.volumes | default "" | nindent 8 }}
      {{ else }}
        {{- toYaml .Values.global.volumes | default "" | nindent 8 }}
      {{ end }}        
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.cli.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.global.secretManager.enabled }}
          env:
            - name: ORAKL_NETWORK_API_URL          
              valueFrom:
                secretKeyRef:
                  name: orakl-cli-secrets
                  key: ORAKL_NETWORK_API_URL
            - name: ORAKL_NETWORK_FETCHER_URL          
              valueFrom:
                secretKeyRef:
                  name: orakl-cli-secrets
                  key: ORAKL_NETWORK_FETCHER_URL
            - name: ORAKL_NETWORK_DELEGATOR_URL          
              valueFrom:
                secretKeyRef:
                  name: orakl-cli-secrets
                  key: ORAKL_NETWORK_DELEGATOR_URL
          {{ else }}
          envFrom:
            - configMapRef:
                name: orakl-cli-configmap
          {{ end }}

          command: ["/bin/sh"]
          args: ["-c", "touch /tmp/healthy; tail -f /dev/null"]          
          volumeMounts:
            # {{- toYaml .Values.global.volumeMounts | default "" | nindent 12 }}          
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe: 
            exec:
              command:
              - ls
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.global.readinessProbe.enabled }}
          readinessProbe: 
            exec:
              command:
              - ls
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}              
          {{- end }}          
          resources:
            {{- toYaml .Values.cli.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
