{{- if .Values.cli.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cli.serviceAccount.name }}
  labels:
    {{- include "orakl-cli.labels.cli" . | nindent 4 }}
  {{- with .Values.cli.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
