apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-cli-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/cli      
      versionId: 1f5cd071-2711-45b1-aaf6-c3cb25ffa2cf
