## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-fetcher #repository url
    pullPolicy: IfNotPresent
    tag: "20230324.0731.7df8358"  
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    REDIS_HOST:
    REDIS_PORT:
    ORAKL_NETWORK_API_URL:
    APP_PORT:

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: ip-10-0-90-13.ap-southeast-1.compute.internal

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

fetcher:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-fetcher
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
  
  resources:
    # limits:
    #   cpu: 1500m
    #   memory: 6Gi
    # requests:
    #   cpu: 1500m
    #   memory: 6Gi

nodeSelector: {}
tolerations: []
dotenv: {}
