## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  name: orakl-fetcher
  namespace: orakl
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-fetcher #repository url
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20240619.0440.07c4a77"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []
  secretManager:
    enabled: false
    secretId:
    versionId:
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  externalIp:
    enabled: false
  podAnnotations: {}
  livenessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
fetcher:
  replicas: 1
  serviceAccount:
    create: true
    name: orakl-fetcher
    annotations: {}
    automountServiceAccountToken: true
  podSecurityContext: {}
  containerSecurityContext: {}
  env:
    - name: CHAIN
      value: cypress
    - name: ORAKL_NETWORK_API_URL
      value: http://orakl-api.orakl.svc.cluster.local:3030/api/v1
    - name: REDIS_HOST
      value: redis-fetcher-master.redis.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
  resources:
    limits:
      cpu: 1000m
      memory: 3Gi
    requests:
      cpu: 1000m
      memory: 3Gi
nodeSelector: {}
tolerations: []
dotenv: {}
