apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.persistentVolume.database.name | default "orakl-database" }}-aggregator-pv"
spec:
  capacity:
    storage: "{{ .Values.persistentVolume.database.size }}"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: "{{ .Values.persistentVolume.efsFileSystemId }}.efs.{{ .Values.persistentVolume.region }}.amazonaws.com"
    path: /db/aggregator/
  storageClassName: orakl-sc    