apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.persistentVolume.database.name | default "orakl-database" }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.database.size }}"
  volumeName:  "{{ .Values.persistentVolume.database.name | default "orakl-database" }}-pv"
  storageClassName: orakl-sc  