{{- if .Values.persistentVolume.efsFileSystemId }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.persistentVolume.database.name | default "orakl-database" }}-pv"
spec:
  capacity:
    storage: "{{ .Values.persistentVolume.database.size }}"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: "{{ .Values.persistentVolume.efsFileSystemId }}.efs.{{ .Values.persistentVolume.region }}.amazonaws.com"
    path: /db/
  storageClassName: orakl-sc    
{{- end }}  