apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-response-listener
  labels:
    {{- include "orakl-request-response.labels.listener" . | nindent 4 }}
spec:
  replicas: {{ .Values.listener.replicas }}
  selector:
    matchLabels:
      {{- include "orakl-request-response.selectorLabels.listener" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orakl-request-response.selectorLabels.listener" . | nindent 8 }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.listener.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.listener.podSecurityContext | nindent 8 }}
      volumes:
      {{ if .Values.global.hostPath.enable }}
        {{- toYaml .Values.global.hostPath.volumes | default "" | nindent 8 }}
      {{ else }}
        {{- if .Values.global.gcpAutopilot.enabled }}
        - name: orakl-log-storage
          persistentVolumeClaim:
            claimName: {{ .Values.global.appName }}-listener-pvc
        {{ else }}
        - name: orakl-log-storage
          persistentVolumeClaim:
            claimName: orakl-log
        {{ end }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.listener.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.listener-tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          volumeMounts:
            {{- toYaml .Values.global.volumeMounts | default "" | nindent 12 }}
          {{- if .Values.global.secretManager.enabled }}
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: NODE_ENV
            - name: ORAKL_NETWORK_API_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: ORAKL_NETWORK_API_URL
            - name: CHAIN
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: CHAIN
            - name: HEALTH_CHECK_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: HEALTH_CHECK_PORT
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: SLACK_WEBHOOK_URL
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: LOG_LEVEL
            - name: LOG_DIR
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: LOG_DIR
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: REDIS_PORT
            - name: PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: PROVIDER_URL
            - name: LISTENER_PORT
              valueFrom:
                secretKeyRef:
                  name: orakl-request-response-secrets
                  key: LISTENER_PORT
          {{ else }}
          envFrom:
            - configMapRef:
                name: orakl-request-response-configmap
          {{ end }}
          command: ["yarn"]
          args: [start:listener:request_response]
          ports:
          - name: healthcheck
            containerPort: {{ .Values.global.config.HEALTH_CHECK_PORT | default 8080 | int }}
          - name: watchman
            containerPort: {{ .Values.listener.APP_PORT | default 4000 | int  }}
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.global.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.listener.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
