apiVersion: v1
kind: Service
metadata:
  name: orakl-core-rr-listener
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    targetPort: http
    protocol: TCP
  selector:
  {{- include "orakl-request-response.selectorLabels.listener" . | nindent 6 }}

