apiVersion: v1
kind: Service
metadata:
  name: {{ include "orakl-request-response.fullname" . }}-listener
  labels: 
    {{- include "orakl-request-response.labels.listener" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    targetPort: http
    protocol: TCP
  selector:
  {{- include "orakl-request-response.selectorLabels.listener" . | nindent 6 }}

