apiVersion: v1
kind: Service
metadata:
  name: request-response-listener
  labels: 
    {{- include "orakl-request-response.labels.listener" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 4000 | int  }}
    protocol: TCP
  selector:
  {{- include "orakl-request-response.selectorLabels.listener" . | nindent 6 }}


