## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-cli
    pullPolicy: IfNotPresent
    tag: "v0.6.0.20230613.0106.de75a96"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    ORAKL_NETWORK_API_URL:
    ORAKL_NETWORK_FETCHER_URL:
    ORAKL_NETWORK_DELEGATOR_URL:
    LISTENER_SERVICE_HOST:
    LISTENER_SERVICE_PORT:
    WORKER_SERVICE_HOST:
    WORKER_SERVICE_PORT:
    REPORTER_SERVICE_HOST:
    REPORTER_SERVICE_PORT:

  secretManager:
    enabled: false
    secretId: 
    versionId: 

  hostPath: 
    enable: false
    volumes:
      # - name: orakl-log-storage
      #   hostPath:
      #     path: /log/
      #     type: DirectoryOrCreate

  volumeMounts:
    # - name: orakl-log-storage
    #   mountPath: /app/log

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: 

  podAnnotations: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

cli:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-cli
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 300m
    #   memory: 500M
    # requests:
    #   cpu: 300m
    #   memory: 500M

nodeSelector: {}
tolerations: []
dotenv: {}
