## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: docker.io/jolol/orakl
    pullPolicy: IfNotPresent
    tag: "v.0.3.0"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    NODE_ENV: production
    CHAIN: localhost
    HOST_SETTINGS_DB_DIR: 
    HEALTH_CHECK_PORT: 8888
    ORAKL_DIR: /app/db
    REDIS_HOST:
    REDIS_PORT: 6379
    SLACK_WEBHOOK_URL: 
    LOG_LEVEL: info
    LOG_DIR: /app/log

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: ip-10-0-90-13.ap-southeast-1.compute.internal

  volumes:
    - name: orakl-database-storage
      persistentVolumeClaim:
        claimName: orakl-database
    - name: orakl-log-storage
      persistentVolumeClaim:
        claimName: orakl-log

  volumeMounts:
    - name: orakl-database-storage
      mountPath: /app/db      
      subPath: db
    - name: orakl-log-storage
      mountPath: /app/log

  podAnnotations: {}

  livenessProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

cli:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-cli
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

nodeSelector: {}
tolerations: []
dotenv: {}
