## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-cli
    pullPolicy: IfNotPresent
    tag: "20230327.0047.545feaa"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    ORAKL_NETWORK_API_URL:
    ORAKL_NETWORK_FETCHER_URL:

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: 

  podAnnotations: {}

  livenessProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

cli:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-cli
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

nodeSelector: {}
tolerations: []
dotenv: {}
