## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  name: orakl-cli
  namespace: orakl
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-cli
    pullPolicy: IfNotPresent
    tag: "v0.6.9.20240528.0711.b1e3128"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []
  secretManager:
    enabled: false
    secretId:
    versionId:
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  podAnnotations: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
cli:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-cli
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true
  podSecurityContext: {}
  containerSecurityContext: {}
  resources:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 1Gi
nodeSelector: {}
tolerations: []
dotenv: {}
