apiVersion: v1
kind: Service
metadata:
  name: request-response-worker
  labels: 
    {{- include "orakl-request-response.labels.worker" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: {{ .Values.listener.APP_PORT | default 5000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 5000 | int  }}
    protocol: TCP

  - name: healthcheck
    port: 8080 
    targetPort: 8080
    protocol: TCP   
  selector:
  {{- include "orakl-request-response.selectorLabels.worker" . | nindent 6 }}

