{
 "title": "VRF",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Events",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) total from sgd1.chain_event"
    }
   ]
  },
  {
   "title": "Latest Block Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select number from chain1.blocks order by number desc limit 1"
    }
   ]
  },
  {
   "title": "VRF Reporter Account Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "select address::text from account where name = 'vrf'"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "select balance from balance where address = '0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec'"
    }
   ]
  },
  {
   "title": "VRF Coordinator Contract Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 3, "y": 3 },
   "targets": [
    {
     "rawSql": "select replace(address::varchar, '\\x', '0x') AS contract from sgd1.chain_event limit 1;"
    }
   ]
  },
  {
   "title": "Min Balance",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 3 },
   "targets": [
    {
     "rawSql": "select (min_balance/1000000000000000000) as min_Balance from sgd1.vrf_min_balance_set"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n(fulfillment_fee/1000000000000000000)  as \"Fulfillment Fee\", \n(base_fee/1000000000000000000)  as \"Base Fee\"\nfrom sgd1.vrf_direct_payment_config_set"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select \nmax_gas_limit as max_gas_limit, \ngas_after_payment_calculation as apc_gas, \nfulfillment_flat_fee_klay_ppm_tier_1 as fee_ppmt_tier1,\nfulfillment_flat_fee_klay_ppm_tier_2 as fee_ppmt_tier2, \nfulfillment_flat_fee_klay_ppm_tier_3 as fee_ppmt_tier3, \nfulfillment_flat_fee_klay_ppm_tier_4 as fee_ppmt_tier4, \nfulfillment_flat_fee_klay_ppm_tier_5 as fee_ppmt_tier5, \nreqs_for_tier_2 as reqs_tier2, \nreqs_for_tier_3 as reqs_tier3, \nreqs_for_tier_4 as reqs_tier4, \nreqs_for_tier_5 as reqs_tier5  \nfrom sgd1.vrf_config_set"
    }
   ]
  },
  {
   "title": "Payment Method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(CASE WHEN is_direct_payment is TRUE then 1 else 0 END) AS direct_Payment, sum(CASE WHEN is_direct_payment is False then 1 else 0 END) AS pre_Payment from sgd1.vrf_random_words_requested"
    }
   ]
  },
  {
   "title": "Registered Proving Keys",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": " select replace(key_hash::varchar, '\\x', '0x') as \"Key Hash\", replace(oracle::varchar, '\\x', '0x') as \"Oracle\"\n from sgd1.vrf_proving_key_registered\n where key_hash not in (select key_hash from sgd1.vrf_proving_key_deregistered)"
    }
   ]
  },
  {
   "title": "Event: Requested&Fulfilled by Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select sum(vrf_random_words_requested) requested, sum(vrf_random_words_fulfilled) fulfilled, time from sgd1.vrf_requested_fulfilled_hour where time <= NOW() - INTERVAL '1 hour' GROUP BY \ntime order by time asc "
    }
   ]
  },
  {
   "title": "Event: Requested&Fulfilled by Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "select sum(vrf_random_words_requested) requested, sum(vrf_random_words_fulfilled) fulfilled, time from sgd1.vrf_requested_fulfilled_min where time <= NOW() - INTERVAL '1 min' GROUP BY \ntime order by time asc "
    }
   ]
  },
  {
   "title": "Requested VS Fulfilled (1 min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n(select count(*) from sgd1.vrf_random_words_requested where to_timestamp(time) > current_timestamp - interval '1 mins') AS random_words_requested,\n(select count(*) from sgd1.vrf_random_words_fulfilled where to_timestamp(time) > current_timestamp - interval '1 mins') AS random_words_fulfilled"
    }
   ]
  },
  {
   "title": "Requested VS Fulfilled (1 hour)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n(select count(*) from sgd1.vrf_random_words_requested where to_timestamp(time) > current_timestamp - interval '1 hours') AS random_words_requested,\n(select count(*) from sgd1.vrf_random_words_fulfilled where to_timestamp(time) > current_timestamp - interval '1 hours') AS random_words_fulfilled"
    }
   ]
  },
  {
   "title": "Requested VS Fulfilled (1 day)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n(select count(*) from sgd1.vrf_random_words_requested where to_timestamp(time) > current_timestamp - interval '24 hours') AS random_words_requested,\n(select count(*) from sgd1.vrf_random_words_fulfilled where to_timestamp(time) > current_timestamp - interval '24 hours') AS random_words_fulfilled"
    }
   ]
  },
  {
   "title": "Last 20 request not fulfilled",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select T1.id, T1.request_id::varchar, T1.acc_id, T1.callback_gas_limit, T1.num_words, replace(T1.sender::varchar, '\\x', '0x') AS sender, T1.is_direct_payment, T1.time from sgd1.vrf_random_words_requested AS T1 LEFT JOIN sgd1.vrf_random_words_fulfilled AS T2 ON T1.request_id = T2.request_id where T2.vid is null order by T1.time desc limit 20;"
    }
   ]
  }
 ]
}