apiVersion: v1
kind: Service
metadata:
  name: vrf-worker
  labels: 
    {{- include "orakl-vrf.labels.worker" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: {{ .Values.listener.APP_PORT | default 5000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 5000 | int  }}
    protocol: TCP

  - name: healthcheck
    port: 8080
    targetPort: 8080
  selector:
    {{- include "orakl-vrf.selectorLabels.worker" . | nindent 6 }}
