apiVersion: v1
kind: Service
metadata:
  name: {{ include "orakl-vrf.fullname" . }}-worker
  labels: 
    {{- include "orakl-vrf.labels.worker" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.worker.APP_PORT | default 4000 | int  }}
    targetPort: {{ .Values.worker.APP_PORT | default 4000 | int  }}
    protocol: TCP
  selector:
    {{- include "orakl-vrf.selectorLabels.worker" . | nindent 6 }}
