apiVersion: v1
kind: ConfigMap
metadata:
  name: logrotate-config
data:
  logrotate.conf: |
    /app/log/*.log {
      size 10K
      daily
      rotate 30
      compress
      delaycompress
      missingok
      notifempty
      create 644 root root
    }