apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: logrotate
spec:
  schedule: "0 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: alpine
              command: ["sh", "-c", "apk update && apk add logrotate && /usr/sbin/logrotate /etc/logrotate.conf"]
              volumeMounts:
                - name: logrotate-config
                  mountPath: /etc/logrotate.conf
                  subPath: logrotate.conf
              volumeMounts:
                - name: orakl-log-storage
                  mountPath: /app/log
          restartPolicy: OnFailure
          volumes:
            - name: logrotate-config
              configMap:
                name: logrotate-config
          volumes:
            - name: orakl-log-storage
              hostPath:
                path: /log/
                type: DirectoryOrCreate
