apiVersion: apps/v1
kind: Deployment
metadata:
  name: orakl-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orakl-cron
  template:
    metadata:
      labels:
        app: orakl-cron
    spec:
      containers:
        - name: orakl-cron
          image: public.ecr.aws/u6t6w0e4/orakl-general:v0.0.0
          volumeMounts:
            - name: logrotate-config
              mountPath: /etc/logrotate.conf
              subPath: logrotate.conf
          volumeMounts:
            - name: orakl-log-storage
              mountPath: /app/log
      volumes:
        - name: logrotate-config
          configMap:
            name: logrotate-config
        - name: orakl-log-storage
          hostPath:
            path: /log/
            type: DirectoryOrCreate
