{{- if .Values.core.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.core.serviceAccount.name }}
  labels:
    {{- include "orakl-request-response.labels.core" . | nindent 4 }}
  {{- with .Values.core.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
