## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/bisonai/orakl-delegator  #repository url
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20230627.0904.6d79d3c"  
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    DATABASE_URL:
    APP_PORT: 
    PROVIDER_URL:

  secretManager:
    enabled: false
    secretId: 
    versionId: 

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: 

  podAnnotations: 
    # vault.hashicorp.com/agent-inject: 'true'
    # vault.hashicorp.com/role: 'internal-app'
    # vault.hashicorp.com/agent-inject-secret-baobab-prod-delegator: 'secret/baobab/prod/delegator'
    # vault.hashicorp.com/agent-inject-template-config: |
    #   {{`- with secret "secret/baobab/prod/delegator" -}}
    #     export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
    #   {{- end `}}    
    # vault.hashicorp.com/agent-limits-ephemeral: "1Gi"

  livenessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

delegator:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: false
    # -- Service account name
    name: internal-app
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
  
  loadBalancerIP: 

  resources:
    limits:
      cpu:
      memory:
    requests:
      cpu:
      memory:

nodeSelector: {}
tolerations: []
dotenv: {}