image:
  repository: asia-southeast1-docker.pkg.dev/bisontry/bisontry/bisontry-balance-checker
  tag: v0.1.0.20231211.1601.c259821

deployment:
  name: bisontry-balance-checker
  replicas: 1
  resources:
