apiVersion: v1
kind: Service
metadata:
  name: { { .Values.deployment.name } }
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: { { .Values.deployment.name } }
