## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: docker.io/jolol/orakl
    pullPolicy: IfNotPresent
    tag: "v.0.0.6"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    NODE_ENV: production
    CHAIN: baobab
    HOST_SETTINGS_DB_DIR: 
    HEALTH_CHECK_PORT: 8888
    ORAKL_DIR: /app/db
    REDIS_HOST: redis-master-0.redis-headless.orakl.svc.cluster.local
    REDIS_PORT: 6379
    SLACK_WEBHOOK_URL: 
    LOG_LEVEL: debug
    LOG_DIR: /app/log

  volumes:
    - name: orakl-database-storage
      persistentVolumeClaim:
        claimName: orakl-database
    - name: orakl-log-storage
      persistentVolumeClaim:
        claimName: orakl-log

  volumeMounts:
    - name: orakl-database-storage
      mountPath: /app/db      
      subPath: db
    - name: orakl-log-storage
      mountPath: /app/log

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

listener:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-request-response-listener
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

worker:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-request-response-worker
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

reporter:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-request-response-reporter
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

nodeSelector: {}
tolerations: []
dotenv: {}
