# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.deployment.name }}
# spec:
#   externalTrafficPolicy: Local
#   type: LoadBalancer
#   loadBalancerClass: tailscale
#   ports:
#     - port: 3030
#       name: http
#       protocol: TCP
#     - protocol: TCP
#       name: tcp
#       port: 10010
#       targetPort: 10010
#   selector:
#     app: {{ .Values.deployment.name }}
