apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  clusterIP: None
  ports:
    - port: 3030
      name: http
      protocol: TCP

  selector:
    app: {{ .Values.deployment.name }}
