{{- if .Values.ingress.enabled -}}
{{- $fullName := include "klaytn.fullname" . -}}
{{- $rpcEnable := include "klaytn.rpc.enable" . -}}
{{- $rpcPort := include "klaytn.rpc.port" . -}}
{{- $wsEnable := include "klaytn.ws.enable" . -}}
{{- $wsPort := include "klaytn.ws.port" . -}}
{{- $network := include "klaytn.network" . -}}

{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "klaytn.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- if eq $rpcEnable "true" }}
          - pathType: ImplementationSpecific
            path: /v1/{{ $network }}/*
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $rpcPort }}
          - pathType: ImplementationSpecific
            path: /v1/baobab/*
            backend:
              service:
                name: {{ $fullName }}-{{ $network }}-klaytn
                port:
                  number: {{ $rpcPort }}
          {{- end }}
          {{- if eq $wsEnable "true" }}
          - pathType: ImplementationSpecific
            path: /v1/ws/*
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $wsPort }}
          {{- end }}
      host: {{ default "" .Values.ingress.host | quote }}

  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
