apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "klaytn.fullname" . }}-logrotate-scripts
  labels:
    {{- include "klaytn.labels" . | nindent 4 }}
data:
  logrotate.sh: |-
    LOG_DIR=$(cat /etc/k*nd/conf/k*nd.conf | grep LOG_DIR | cut -d '=' -f 2)
    cat <<EOF > /etc/logrotate.d/klaytn
    $LOG_DIR/*.out {
        daily
        copytruncate
        compress
        rotate 7
        dateext
        create 0644 root root
    }
    EOF