apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "klaytn.fullname" . }}-scripts
  labels:
    {{- include "klaytn.labels" . | nindent 4 }}
data:
  init_script.sh: |-
    # DATE=$(date -d @$(($(date +%s) - 86400)) +%Y%m%d)
    # NETWORK={{ .Values.node.network }}
    # IS_CHAINDATA=false

    if [ -d "/klaytn/klay" ]; then
      echo "done"
    else
      mkdir -p /klaytn
      cd /klaytn
      wget ${INIT_DATA_URL} -O - | tar -xzvf -
      echo "done"
    fi

    #   # if wget --spider --no-check-certificate ${INIT_DATA_URL}; then
      
    #   #   if [ -d "/klaytn/klay" ]; then
    #   #     echo "done"
    #   #   else
    #   #     mkdir -p /klaytn
    #   #     cd /klaytn
    #   #     wget ${INIT_DATA_URL} -O - | tar -xzvf -
    #   #     echo "done"
    #   #   fi
    #   #   break
    #   # fi
    # done
