{{- $fullName := include "klaytn.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "klaytn.labels" . | nindent 4 }}
    app.kubernetes.io/component: ken
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ $fullName }}
  selector:
    matchLabels:
      {{- include "klaytn.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "klaytn.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not .Values.enableServiceLinks }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "klaytn.serviceAccountName" . }}
      securityContext: 
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-data-url
          image: curlimages/curl:latest
          command: 
            - /bin/sh
            - -c
            - export INIT_DATA_URL=$(curl -s https://packages.klaytn.net/cypress/chaindata/ | grep latest |awk -F'"' '{print $2}')
        - name: init-chain-data
          image: busybox:latest
          command: 
            - /bin/sh
            - -c
            - /tmp/init_script.sh
          volumeMounts:
            - name: data
              mountPath: /klaytn
            - name: scripts
              mountPath: /tmp/
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: []
          # envFrom:
          #   - configMapRef:
          #       name: {{ $fullName }}-datadog-config
          command: 
            {{- toYaml .Values.command | nindent 12 }}
          ports:
            - name: ken
              containerPort: {{ .Values.node.port }}
              protocol: TCP
            {{- if .Values.node.rpc.enable }}
            - name: rpc
              containerPort: {{ .Values.node.rpc.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.node.ws.enable }}
            - name: ws
              containerPort: {{ .Values.node.ws.port }}
              protocol: TCP
            {{- end }}
            - name: prometheus
              containerPort: 61001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: prometheus
          readinessProbe:
            httpGet:
              path: /metrics
              port: prometheus
          volumeMounts:
            - name: data
              mountPath: {{ .Values.node.dataDir }}
            - name: config
              mountPath: /klaytn-docker-pkg/conf/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}-node-config
        - name: scripts
          configMap:
            name: {{ $fullName }}-scripts
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}


