apiVersion: v1
kind: Service
metadata:
  name: aggregator-reporter
  labels: 
    {{- include "orakl-aggregator.labels.reporter" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    {{- include "orakl-aggregator.selectorLabels.reporter" . | nindent 6 }}
