apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  ports:
    - port: 5050
      targetPort: http
      protocol: TCP
  type: {{ .Values.bootApi.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
