apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  ports:
    - port: 5050
      targetPort: http
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 34.87.152.175 #TODO: Change this value
  selector:
    app: {{ .Values.deployment.name }}
