{{- if .Values.config.efsFileSystemId }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.name | default "orakl-log" }}-pv"
spec:
  capacity:
    storage: "{{ .Values.config.size }}"
    
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: "{{ .Values.config.efsFileSystemId }}.efs.{{ .Values.config.region }}.amazonaws.com"
    path: /log/
  storageClassName: orakl-sc    
  {{- end }}