cloud: gcp
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

initContainer:

imagePullSecrets: []
image:
  repository: klaytn/klaytn
  pullPolicy: Always
  tag: latest

node:
  initData: true
  # chainDataUrl: https://s3.ap-northeast-2.amazonaws.com/klaytn-chaindata/baobab/klaytn-baobab-chaindata-20221202011211.tar.gz
  # chainDataUrl: https://s3.ap-northeast-2.amazonaws.com/klaytn-chaindata/cypress/klaytn-cypress-chaindata-20221201011211.tar.gz
  
  type: en
  network: cypress   
  port: 32323
  syncMode: "full"
  verbosity: 3
  # maxconnections: 10
  metrics: true
  prometheus: true
  dbNoParallelWrite: false
  multichannel: true
  noDiscovery: false
  bootnodes: ""
  dataDir: /klaytn

  server:
    type: "fasthttp"

  txpool:
    execSlotsAll: 4096
    execSlotsAccount: 4096
    nonexecSlotsAll: 4096
    nonexecSlotsAccount: 4096
    lifeTime: 30m

  rpc:
    enable: true
    port: 8551
    # admin, debug, klay, miner, net, personal, rpc, txpool, web3
    api: [klay,eth,net,web3]
    addr: 0.0.0.0
    cors: ["*"]
    vhosts: ["*"]

  ws:
    enable: false
    port: 8552
    # admin, debug, klay, miner, net, personal, rpc, txpool, web3
    api: [klay,eth,net,web3]
    addr: 0.0.0.0
    origins: []

  additional: [
    --sendertxhashindexing,
    --txpool.deny.remotetx,
    --state.tries-in-memory 50,
    --state.trie-cache-limit 10240,
    --rpc.concurrencylimit 8000,
    --api.filter.getLogs.deadline 300ms,
  ]

enableServiceLinks: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8551":"ken-cypress-klaytn","61001":"ken-cypress-klaytn"}}'
    cloud.google.com/neg: '{"ingress": true}'
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "klaytn"
  host: ""
  tls: []

command: 
  - /bin/sh
  - -c
  - |
    kend start
    sleep infinity

resources: 
  requests: 
    cpu: 4000m
    memory: 16Gi

# updateStrategy:
#   rollingUpdate:
#     maxUnavailable:

# baobab: https://packages.klaytn.net/baobab/chaindata/ (163.0GB / 296.9GB uncompressed)
# cypress: https://packages.klaytn.net/cypress/chaindata/ (756.0GB / 2.2TB uncompressed)
persistence:
  size: "3Ti"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

affinity: {}

topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/component: ken
