persistentVolume:
  datbase:
    name: orakl-database
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /
    size: 20M
    subPath: ""
    storageClass: orakl-default-sc
  log:
    name: orakl-log
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /
    size: 2Gi
    subPath: ""
    storageClass: orakl-default-sc
