global:
  image:
    repository: docker.io/jolol/orakl
    pullPolicy: IfNotPresent
    tag: "v.0.0.0"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    NODE_ENV:
    CHAIN:
    HOST_SETTINGS_DB_DIR: 
    HEALTH_CHECK_PORT:
    ORAKL_DIR:
    SLACK_WEBHOOK_URL:

  podAnnotations: {}

  healthCheckPort: 8888

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 