## created by Bisonai

global:
  name: orakl-reporter
  namespace: orakl
  image:
    repository: public.ecr.aws/bisonai/orakl-reporter
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20250404.0429.5013bf3"
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  podAnnotations: {}
  livenessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
reporter:
  annotations: {}
  replicas: 1
  podSecurityContext: {}
  containerSecurityContext: {}
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  env:
    - name: USE_VAULT
      value: "true"
    - name: VAULT_ADDR
      value: http://172.0.100.185:8200/
    - name: JWT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: VAULT_ROLE
      value: orakl
    - name: VAULT_SECRET_PATH
      value: cypress
    - name: VAULT_KEY_NAME
      value: reporter
    - name: DAL_WS_URL
      value: "ws://dal.cypress.orakl.network/ws"
    - name: DAL_REST_URL
      value: "https://dal.cypress.orakl.network"
    - name: LOG_LEVEL
      value: "debug"
    - name: CHAIN
      value: "cypress"
    - name: SUBMISSION_PROXY_CONTRACT
      value: "0xcb56b163e545a3870ca04c6ae2401f2405fb29a9"
    - name: KAIA_PROVIDER_URL
      value: "https://freely-inspired-ram.n0des.xyz"
    - name: KAIA_WEBSOCKET_URL
      value: wss://public-en.node.kaia.io/ws
    - name: DELEGATOR_URL
      value: "http://orakl-delegator.orakl.svc.cluster.local"
nodeSelector: {}
tolerations: []
dotenv: {}
deployment:
  name: orakl-reporter
  replicas: 1
