## created by Bisonai

global:
  name: orakl-reporter
  namespace: orakl
  image:
    repository: public.ecr.aws/bisonai/orakl-reporter
    pullPolicy: IfNotPresent
    tag: ""
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  podAnnotations: {}
  livenessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
reporter:
  annotations: {}
  replicas: 1
  podSecurityContext: {}
  containerSecurityContext: {}
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: DAL_WS_URL
      value: "ws://dal.baobab.orakl.network/ws"
    - name: LOG_LEVEL
      value: "error"
    - name: CHAIN
      value: "cypress"
    - name: SUBMISSION_PROXY_CONTRACT
      value: "0x07ec1e04353d0368ab9c6165dac2a0be51cfb1fe"
    - name: VAULT_ADDR
      value: http://172.0.100.165:8200/
    - name: VAULT_ROLE
      value: orakl
    - name: VAULT_SECRET_PATH
      value: baobab
    - name: VAULT_KEY_NAME
      value: reporter
nodeSelector: {}
tolerations: []
dotenv: {}
deployment:
  name: orakl-reporter
  replicas: 1
