apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: orakl
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      imagePullSecrets:
        - name: gar-json-key
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          command: ["/bin/sh","-c"]
          args: [". /vault/secrets/config && node ./dist/main"]            
          env:
            - name: VAULT_ADDR
              value: http://vault.vault.svc.cluster.local:8200/
            - name: JWT_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: VAULT_ROLE