apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: orakl
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}
  loadBalancerSourceRanges:
    - 0.0.0.0/0