apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: orakl
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: {{ .Values.deployment.name }}