apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: orakl
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}