apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  # type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  type: LoadBalancer
  {{- if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ .Values.deployment.name }}
