## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  name: vrf
  namespace: orakl

  appName: orakl-vrf
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-core #repository url
    pullPolicy: IfNotPresent
    listenerTag: "v0.5.1.20240223.0352.eec1c2d"
    reporterTag: "v0.5.1.20240223.0352.eec1c2d"
    workerTag: "v0.5.1.20240223.0352.eec1c2d"
    tag: "v0.5.1.20240223.0352.eec1c2d"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  env:
    LOG_LEVEL: info

  secretManager:
    enabled: false
    secretId:
    versionId:

  gcpAutopilot:
    enabled: false

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: ip-10-0-176-73.ap-southeast-1.compute.internal

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

listener:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-listener
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT: 4000

  podSecurityContext: {}

  containerSecurityContext: {}

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi

worker:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-worker
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT: 5000

  podSecurityContext: {}

  containerSecurityContext: {}

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi

reporter:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-reporter
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT: 6000

  podSecurityContext: {}

  containerSecurityContext: {}

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

nodeSelector: {}
tolerations: []
dotenv: {}
