## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-core #repository url
    pullPolicy: IfNotPresent
    tag: "20230327.0047.545feaa"                    #image tag
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    NODE_ENV: 
    ORAKL_NETWORK_API_URL:
    CHAIN:
    HEALTH_CHECK_PORT:
    REDIS_HOST:
    REDIS_PORT:
    SLACK_WEBHOOK_URL:
    LOG_LEVEL: debug
    LOG_DIR: 


  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: ip-10-0-176-73.ap-southeast-1.compute.internal

  hostPath: 
    enable: true
    volumes:
      - name: orakl-log-storage
        hostPath:
          path: /log/
          type: DirectoryOrCreate

  volumeMounts:
    - name: orakl-log-storage
      mountPath: /app/log

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

listener:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-listener
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT: 4000

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

worker:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-worker
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

reporter:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-vrf-reporter
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true
  
  APP_PORT: 6000

  podSecurityContext: {}

  containerSecurityContext: {}
    
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 4Gi
    # requests:
    #   cpu: 500m
    #   memory: 4Gi

nodeSelector: {}
tolerations: []
dotenv: {}
