global:
  name: admin
  namespace: orakl

image:
  repository: public.ecr.aws/bisonai/orakl-general
  tag: admin.v0.1.0.20230802.0109.13ce71f

deployment:
  name: orakl-admin
  replicas: 1
  resources:

probes:
  liveness:
    path: /
    port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /
    port: 3000
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
