{{- if .Values.global.gcpAutopilot.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.global.appName }}-listener-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.global.appName }}-reporter-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.global.appName }}-worker-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi        
{{- end}}