apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-core-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/core
      versionId: e6e7591a-708e-4b63-8c26-73b2fcae60ae
