apiVersion: v1
data:
  haproxy.cfg: |-
    global
    defaults
        timeout client          30s
        timeout server          30s
        timeout connect         30s
 
    frontend frontend
        bind    0.0.0.0:5432
        default_backend backend
 
    backend backend
        mode                    tcp
        server upstream orakl-bisonai-baobab.c4fxu3k4a1gu.ap-southeast-1.rds.amazonaws.com:5432
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: orakl-haproxy-port-forward

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: orakl-forward-pod
  name: orakl-forward-pod
spec:
  containers:
    - command:
      - haproxy
      - -f
      - /usr/local/etc/haproxy/haproxy.cfg
      - -V
      image: haproxy:1.7-alpine
      name: orakl-forward-pod
      resources: {}
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/
          name: orakl-haproxy-port-forward
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: orakl-haproxy-port-forward
      configMap:
        name: orakl-haproxy-port-forward
status: {}