apiVersion: v1
data:
  haproxy.cfg: |-
    global
    defaults
        timeout client          30s
        timeout server          30s
        timeout connect         30s

    frontend frontend_8551
        bind    0.0.0.0:8551
        default_backend backend_8551

    frontend frontend_8556
        bind    0.0.0.0:8556
        default_backend backend_8556

    backend backend_8551
        mode                    tcp
        server upstream_bridge-en-8551 bridge-en.marblex.io:8551

    backend backend_8556
        mode                    tcp
        server upstream_bridge-en-8556 game-en.marblex.io:8551

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mbx-haproxy-port-forward

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mbx-forward-pod
  name: mbx-forward-pod
spec:
  containers:
    - command:
      - haproxy
      - -f
      - /usr/local/etc/haproxy/haproxy.cfg
      - -V
      image: haproxy:1.7-alpine
      name: mbx-forward-pod
      resources: {}
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/
          name: mbx-haproxy-port-forward
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: mbx-haproxy-port-forward
      configMap:
        name: mbx-haproxy-port-forward
status: {}