{{- if .Values.global.secretManager.enabled }}
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-fetcher-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.global.secretManager.secretId }}
      versionId: {{ .Values.global.secretManager.versionId }}
{{ end }}