apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-fetcher-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/fetcher
      versionId: 53b83da9-8a9c-4c3b-947d-3f858a125214
