{{- if .Values.global.secretManager.enabled }}
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-fetcher-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/fetcher
      versionId: 774d6850-2482-46ad-bc09-86a1b04012c8 
{{ end }}