apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fetcher.serviceAccount.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.global.config.APP_PORT | default 4040 | int  }}
    targetPort: http
    protocol: TCP
