apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orakl-ingress
  namespace: orakl
  labels:
    app: orakl-ingress
  annotations:
    projectcontour.io/ingress.class: "contour"

spec:
  ingressClassName: contour
  rules:
  - host: baobab.pod-api.orakl.network
    http:
      paths:
      - backend:
          service:
            name: orakl-api
            port:
              number: 3030
        pathType: Prefix
        path: /
  
  - host: baobab.pod-delegator.orakl.network
    http:
      paths:
      - backend:
          service:
            name: orakl-delegator
            port:
              number: 80
        pathType: Prefix
        path: /

  - host: baobab.pod-node.orakl.network
    http:
      paths:
        - backend:
            service:
              name: orakl-node
              port:
                number: 3030
          pathType: Prefix
          path: /

  - host: baobab.pod-por.orakl.network
    http:
      paths:
        - backend:
            service:
              name: orakl-por
              port:
                number: 3000
          pathType: Prefix
          path: /