image:
  repository: public.ecr.aws/bisonai/orakl-general
  tag: monitor.v0.0.1.20230428.0048.75df81a

config:
  PROVIDER: "http://10.0.64.10:8282"

  MONITOR_POSTGRES_USER: 
  MONITOR_POSTGRES_PASSWORD: 
  MONITOR_POSTGRES_HOST: 
  MONITOR_POSTGRES_PORT: 
  MONITOR_POSTGRES_DATABASE: 

  ORAKL_POSTGRES_USER: 
  ORAKL_POSTGRES_PASSWORD: 
  ORAKL_POSTGRES_HOST: 
  ORAKL_POSTGRES_PORT: 
  ORAKL_POSTGRES_DATABASE: 

  GRAPH_NODE_POSTGRES_USER: 
  GRAPH_NODE_POSTGRES_PASSWORD: 
  GRAPH_NODE_POSTGRES_HOST: 
  GRAPH_NODE_POSTGRES_PORT: 
  GRAPH_NODE_POSTGRES_DATABASE: 

deployment:
  name: orakl-monitor-api
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi

probes:
  liveness:
    path: /health
    port: 8888
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health
    port: 8888
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
