apiVersion: v1
kind: Service
metadata:
  name: orakl-api
spec:
  type: ClusterIP
  ports:
  - port: 3030
    targetPort: http
    protocol: TCP
  selector:
    {{- include "orakl-api.selectorLabels.api" . | nindent 6 }}