apiVersion: v1
kind: Service
metadata:
  name: orakl-api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.global.config.APP_PORT | default 3030 | int  }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "orakl-api.selectorLabels.api" . | nindent 6 }}   
