kind: ServiceAccount
apiVersion: v1
metadata:
  name: orakl-por
  namespace: orakl

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: proof-of-reserve
  namespace: orakl
  labels:
    app.kubernetes.io/instance: "proof-of-reserve"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 30
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: "proof-of-reserve"
        spec:
          serviceAccountName: orakl-por
          restartPolicy: Never
          containers:
            - name: proof-of-reserve
              image: public.ecr.aws/u6t6w0e4/orakl-core:v0.5.1.20240122.0240.1672788
              imagePullPolicy: IfNotPresent
              command: ["yarn"]
              args: [start:por]
              env:
                - name: NODE_ENV
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: NODE_ENV
                - name: ORAKL_NETWORK_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: ORAKL_NETWORK_API_URL
                - name: ORAKL_NETWORK_DELEGATOR_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: ORAKL_NETWORK_DELEGATOR_URL
                - name: CHAIN
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: CHAIN
                - name: LOG_LEVEL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: LOG_LEVEL
                - name: REDIS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: REDIS_PORT
                - name: PROVIDER_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: PROVIDER_URL
                - name: POR_AGGREGATOR_HASH
                  value: "0x4a4f59a3cc46b134755831fc93da7e3ce133b98d358afe87e5d16e72c823b4a9"
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-secrets
                      key: SLACK_WEBHOOK_URL
