kind: ServiceAccount
apiVersion: v1
metadata:
  name: orakl-por
  namespace: orakl

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: proof-of-reserve
  namespace: orakl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 30
      template:
        spec:
          serviceAccountName: orakl-por
          restartPolicy: Never
          containers:
          - name: proof-of-reserve
            image: public.ecr.aws/u6t6w0e4/orakl-core:v0.5.0.20231115.0418.edbde75
            imagePullPolicy: IfNotPresent
            command: ["yarn"]
            args: [start:por]
            env:
              - name: NODE_ENV
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: NODE_ENV
              - name: ORAKL_NETWORK_API_URL
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: ORAKL_NETWORK_API_URL
              - name: ORAKL_NETWORK_DELEGATOR_URL
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: ORAKL_NETWORK_DELEGATOR_URL
              - name: CHAIN
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: CHAIN
              - name: LOG_LEVEL
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: LOG_LEVEL
              - name: REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: REDIS_HOST
              - name: REDIS_PORT
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: REDIS_PORT
              - name: PROVIDER_URL
                valueFrom:
                  secretKeyRef:
                    name: aggregator-secrets
                    key: PROVIDER_URL
              - name: POR_AGGREGATOR_HASH
                value: "0xdfc65be0daca54cfd5c081bb325d855e71b1a9cd6d2c5e44fcc1d7d0756f7811"
