apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.global.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.global.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "orakl-vrf.labels.listener" . | nindent 4 }}
  name: orakl-database
spec:
  accessModes:
{{ toYaml .Values.global.persistentVolume.accessModes | indent 4 }}
{{- if .Values.global.persistentVolume.storageClass }}
{{- if (eq "-" .Values.global.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.global.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.global.persistentVolume.volumeBindingMode }}
  volumeBindingMode: "{{ .Values.global.persistentVolume.volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.global.persistentVolume.size }}"
{{- if .Values.global.persistentVolume.selector }}
  selector:
  {{- toYaml .Values.global.persistentVolume.selector | nindent 4 }}
{{- end -}}
{{- if .Values.global.persistentVolume.volumeName }}
  volumeName: "{{ .Values.global.persistentVolume.volumeName }}"
{{- end -}}

