apiVersion: v1
kind: Service
metadata:
  name: orakl-core-vrf-listener
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 6000 | int  }}
    targetPort: http
    protocol: TCP
  selector:
  {{- include "orakl-vrf.selectorLabels.listener" . | nindent 6 }}

