apiVersion: v1
kind: Service
metadata:
  name: {{ include "orakl-vrf.fullname" . }}-listener
  labels: 
    {{- include "orakl-vrf.labels.listener" . | nindent 4 }}  
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.APP_PORT | default 3000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 3000 | int  }}
    protocol: TCP
  selector:
    {{- include "orakl-vrf.selectorLabels.listener" . | nindent 6 }}
