image:
  repository: asia-southeast1-docker.pkg.dev/bisontry/bisontry/bisontry-health-checker
  tag: v0.1.0.20240216.0351.30594bb

deployment:
  name: bisontry-health-checker
  replicas: 1
  resources:
