apiVersion: v1
kind: Service
metadata:
  name: orakl-monitor-api
spec:
  type: LoadBalancer
  loadBalancerIP: 34.142.143.138
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
  selector:
    {{- include "orakl-monitor-api.selectorLabels.monitor-api" . | nindent 6 }}
