apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }} 
spec:
  type: LoadBalancer
  {{- with .Values.service }}
  loadBalancerIP: {{ .loadBalancerIP | quote }}
  {{- end }}
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
  selector:
    {{- include "orakl-monitor-api.selectorLabels.monitor-api" . | nindent 6 }}
