image:
  repository: asia-southeast1-docker.pkg.dev/vpc-host-orakl-prod/orakl/orakl-backend-fe
  tag: "v0.0.1.20250404.0429.5013bf3"
tlsSecretName: orakl-backend-fe-tls

deployment:
  name: orakl-backend-fe
  replicas: 1
  resources:
