## Orakl Sentinel Helm Chart
## created by Bisonai
global:
  name: orakl-sentinel
  namespace: orakl

  image:
    repository: public.ecr.aws/bisonai/orakl-sentinel
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20240625.0255.5673f9d"
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: "orakl-sentinel"

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /api/v1
    port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /api/v1
    port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

app:
  enabled: true
  replicas: 1
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'orakl'
    vault.hashicorp.com/agent-inject-template-config: |
      {{ with secret "baobab/data/monitor" -}}
        #!/bin/bash
        export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
      {{- end }}
  serviceAccount:
    create: false
    name:
    annotations: {}
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}

  port: "3000"

  args: "sentinelbin"

  env:
    - name: VAULT_ADDR
      value: http://172.0.100.165:8200/
    - name: JWT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: VAULT_ROLE
      value: orakl
    - name: VAULT_SECRET_PATH
      value: baobab
    - name: VAULT_KEY_NAME
      value: monitor
    - name: LOG_LEVEL
      value: debug
    - name: CHAIN
      value: baobab
    - name: HEALTH_CHECK_INTERVAL
      value: "10s"
    - name: BALANCE_CHECK_INTERVAL
      value: "60s"
    - name: BALANCE_ALARM_INTERVAL
      value: "30m"
    - name: SUBMITTER_ALARM_AMOUNT
      value: "25"
    - name: DELEGATOR_ALARM_AMOUNT
      value: "10000"
    - name: EVENT_CHECK_INTERVAL
      value: "60s"
    - name: JSON_RPC_URL
      value: http://172.0.100.240:8551
    - name: ORAKL_API_URL
      value: http://orakl-api.orakl.svc.cluster.local:3030/api/v1
    - name: ORAKL_NODE_ADMIN_URL
      value: http://orakl-node.orakl.svc.cluster.local:3030/api/v1
    - name: ORAKL_DELEGATOR_URL
      value: http://orakl-delegator.orakl.svc.cluster.local/api/v1
    - name: POR_URL
      value: http://orakl-por.orakl.svc.cluster.local:3000/api/v1
    - name: SUBMISSION_PROXY_CONTRACT
      value: "0xde8fb45ff8e330ccf8e5cc0913ee0143b2a0ebdb"
  resources:
    limits:
      cpu: 100m
      memory: 0.5Gi
    requests:
      cpu: 100m
      memory: 0.5Gi

nodeSelector: {}
tolerations: []
dotenv: {}
