{{- if .Values.reporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.reporter.serviceAccount.name }}
  labels:
    {{- include "orakl-request-response.labels.reporter" . | nindent 4 }}
  {{- with .Values.reporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
