apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-reporter
  labels: 
    {{- include "orakl-request-response.labels.reporter" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: 6000
    targetPort: 6000
    protocol: TCP
  - name: healthcheck
    port: 8080 
    targetPort: 8080
    protocol: TCP    
  selector:
  {{- include "orakl-request-response.selectorLabels.reporter" . | nindent 6 }}

