apiVersion: v1
kind: Service
metadata:
  name: request-response-reporter
  labels: 
    {{- include "orakl-request-response.labels.reporter" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: watchman
    port: {{ .Values.listener.APP_PORT | default 6000 | int  }}
    targetPort: {{ .Values.listener.APP_PORT | default 6000 | int  }}
    protocol: TCP

  - name: healthcheck
    port: {{ .Values.global.config.HEALTH_CHECK_PORT | default 8080 | int }} 
    targetPort: {{ .Values.global.config.HEALTH_CHECK_PORT | default 8080 | int }}
    protocol: TCP    
  selector:
  {{- include "orakl-request-response.selectorLabels.reporter" . | nindent 6 }}

