## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: public.ecr.aws/u6t6w0e4/orakl-core #repository url
    pullPolicy: IfNotPresent
    tag: "v.20230413.0102.ae89852"  
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    NODE_ENV: 
    ORAKL_NETWORK_API_URL:
    CHAIN:
    HEALTH_CHECK_PORT:
    REDIS_HOST: "10.0.108.117"
    REDIS_PORT:
    SLACK_WEBHOOK_URL:
    LOG_LEVEL: debug
    LOG_DIR: 
    PROVIDER_URL: https://baobab01.fautor.app
    PUBLIC_KEY:
    PRIVATE_KEY:

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: 

  hostPath: 
    enable: false
    volumes:
      - name: orakl-log-storage
        hostPath:
          path: /log/
          type: DirectoryOrCreate

  volumes:
    - name: orakl-log-storage
      persistentVolumeClaim:
        claimName: orakl-log

  volumeMounts:
    - name: orakl-log-storage
      mountPath: /app/log

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

listener:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-aggregator-listener
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT : 4000

  podSecurityContext: {}

  containerSecurityContext: {}
    
  # resources:
  #   limits:
  #     cpu: 400m
  #     memory: 2Gi
  #   requests:
  #     cpu: 400m
  #     memory: 2Gi

worker:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-aggregator-worker
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
    
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 4Gi
  #   requests:
  #     cpu: 1000m
  #     memory: 4Gi

reporter:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-aggregator-reporter
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  APP_PORT : 6000

  podSecurityContext: {}

  containerSecurityContext: {}
    
  # resources:
  #   limits:
  #     cpu: 400m
  #     memory: 2Gi
  #   requests:
  #     cpu: 400m
  #     memory: 2Gi

nodeSelector: {}
tolerations: []
dotenv: {}
