apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orakl-vrf.fullname" . }}-listener
  labels:
    {{- include "orakl-listener.labels.listener" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orakl-listener.selectorLabels.listener" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orakl-listener.selectorLabels.listener" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orakl-listener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: postgres_host
              valueFrom:
                secretKeyRef:
                  name: orakl-listener-config
                  key: postgres_host
            - name: postgres_user
              valueFrom:
                secretKeyRef:
                  name: orakl-listener-config
                  key: postgres_user
            - name: postgres_pass
              valueFrom:
                secretKeyRef:
                  name: orakl-listener-config
                  key: postgres_pass
            - name: postgres_db
              valueFrom:
                secretKeyRef:
                  name: orakl-listener-config
                  key: postgres_db
            - name: ipfs
              valueFrom:
                secretKeyRef:
                  name: orakl-listener-config
                  key: ipfs

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: ws
              containerPort: 8001
              protocol: TCP
            - name: admin
              containerPort: 8020
              protocol: TCP
            - name: prometheus
              containerPort: 8040
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
