apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mbxnft-backend.fullname" . }}
  labels:
    {{- include "mbxnft-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mbxnft-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mbxnft-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mbxnft-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_REGION
            - name: AWS_S3_BASE_PATH
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_S3_BASE_PATH
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_S3_BUCKET_NAME
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: AWS_WEB_IDENTITY_TOKEN_FILE
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: BASE_URL
            - name: BULL_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: BULL_REDIS_HOST
            - name: BULL_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: BULL_REDIS_PORT
            - name: COIN_MARKET_CAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: COIN_MARKET_CAP_API_KEY
            - name: COIN_MARKET_CAP_CRON
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: COIN_MARKET_CAP_CRON
            - name: ETHERS_NETWORK_CHAIN
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: ETHERS_NETWORK_CHAIN
            - name: ETHERS_NETWORK_NAME
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: ETHERS_NETWORK_NAME
            - name: ETHERS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: ETHERS_PRIVATE_KEY
            - name: ETHERS_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: ETHERS_URL
            - name: ETL_GRAPHQL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: ETL_GRAPHQL_ENDPOINT
            - name: IMGPROXY_HOST
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: IMGPROXY_HOST
            - name: IMGPROXY_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: IMGPROXY_KEY
            - name: IMGPROXY_SALT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: IMGPROXY_SALT
            - name: IPFS_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: IPFS_URL
            - name: MAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MAIL_SENDER
            - name: PUBSUB_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: PUBSUB_REDIS_HOST
            - name: PUBSUB_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: PUBSUB_REDIS_PORT
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SENTRY_DSN
            - name: SENTRY_ENV
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SENTRY_ENV
            - name: SUBGRAPH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SUBGRAPH_ENDPOINT
            - name: SUBGRAPH_WS_PORT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SUBGRAPH_WS_PORT
            - name: TYPEORM_LOG
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: TYPEORM_LOG
            - name: TYPEORM_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: TYPEORM_URL
            - name: UPDATE_GAME_VOLS_CRON
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: UPDATE_GAME_VOLS_CRON
            - name: WEB3_TOKEN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: WEB3_TOKEN_DOMAIN
            - name: MBX_TX_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MBX_TX_URL
            - name: MBX_TX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MBX_TX_TOKEN                                   
            - name: GRAPH_NODE_HOST
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_HOST      
            - name: GRAPH_NODE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_USERNAME
            - name: GRAPH_NODE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_PASSWORD
            - name: GRAPH_NODE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_DATABASE
            - name: GRAPH_NODE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_SCHEMA      
            - name: GRAPH_NODE_PORT
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: GRAPH_NODE_PORT               
            - name: CLIENT_COUNTRY_INFO_REQUEST_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: CLIENT_COUNTRY_INFO_REQUEST_URL                      
            - name: CLIENT_COUNTRY_INFO_REQUEST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: CLIENT_COUNTRY_INFO_REQUEST_API_KEY                      
            - name: SEND_PURCHASE_INFO_DATA_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SEND_PURCHASE_INFO_DATA_URL                      
            - name: SEND_PURCHASE_INFO_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: SEND_PURCHASE_INFO_DATA_API_KEY                      
            - name: MBX_MNS_URL
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MBX_MNS_URL                      
            - name: MBX_MNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MBX_MNS_API_KEY 
            - name: MBX_MARKET_CAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mbxnft-backend-config
                  key: MBX_MARKET_CAP_API_KEY                                           
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
