apiVersion: v1
kind: Service
metadata:
  name: {{ include "mbxnft-backend.fullname" . }}-admin
  labels:
    {{- include "mbxnft-backend.labels.admin" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mbxnft-backend.selectorLabels.admin" . | nindent 4 }}
