apiVersion: v1
kind: ConfigMap
metadata:
  name: orakl-aggregator-configmap
data:
  NODE_ENV: "{{ .Values.global.config.NODE_ENV }}"
  CHAIN: "{{ .Values.global.config.CHAIN }}"  
  PROVIDER_URL: "{{ .Values.global.config.PROVIDER_URL }}"
  ORAKL_NETWORK_API_URL: "{{ .Values.global.config.ORAKL_NETWORK_API_URL }}"
  ORAKL_NETWORK_DELEGATOR_URL: "{{ .Values.global.config.ORAKL_NETWORK_DELEGATOR_URL }}"
  LOG_LEVEL: "{{ .Values.global.config.LOG_LEVEL }}"
  LOG_DIR: "{{ .Values.global.config.LOG_DIR }}"  
  REDIS_HOST: "{{ .Values.global.config.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.global.config.REDIS_PORT }}"
  SLACK_WEBHOOK_URL: "{{ .Values.global.config.SLACK_WEBHOOK_URL }}"
