apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: orakl-aggregator-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/core
      versionId: b314fab0-9d84-4d4c-8c52-1582431fc348
