{{- if .Values.global.secretManager.enabled }}
apiVersion: mumoshu.github.io/v1alpha11
kind: AWSSecret
metadata:
  name: orakl-aggregator-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.global.secretManager.secretId }}
      versionId: {{ .Values.global.secretManager.versionId }}
{{- end}}