{{- if .Values.global.secretManager.enabled }}
apiVersion: mumoshu.github.io/v1alpha11
kind: AWSSecret
metadata:
  name: orakl-aggregator-secrets
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: orakl/baobab/core
      versionId: 3fc054ec-a478-43a2-9b44-ba25b212df15
{{- end}}