apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: REDIS_HOST
            value: "{{ .Values.deployment.env.REDIS_HOST }}"
          - name: REDIS_PORT
            value: "{{ .Values.deployment.env.REDIS_PORT }}"
          - name: NODE_ENV
            value: "{{ .Values.deployment.env.NODE_ENV }}"
          - name: PORT
            value: "{{ .Values.deployment.env.PORT }}"
          - name: BULL_WATCH_QUEUE_PREFIXES
            value: "{{ .Values.deployment.env.BULL_WATCH_QUEUE_PREFIXES }}"
          - name: UI
            value: "{{ .Values.deployment.env.UI }}"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi          
        ports:
        - name: http
          containerPort: {{ .Values.deployment.env.PORT }}
