apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}