## created by Bisonai

global:
  name: orakl-logscribe
  namespace: orakl
  image:
    repository: public.ecr.aws/bisonai/orakl-logscribe
    pullPolicy: IfNotPresent
    tag: ""
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  podAnnotations: {}
  livenessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 6
    timeoutSeconds: 6
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    path: /api/v1
    initialDelaySeconds: 10
    periodSeconds: 6
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 5
logscribe:
  enabled: true
  replicas: 1
  podSecurityContext: {}
  containerSecurityContext: {}
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
nodeSelector: {}
tolerations: []
dotenv: {}
deployment:
  name: orakl-logscribe
  replicas: 1
