image:
  repository: ejhayes/nodejs-bull-monitor
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: vrf-monitor
  type: ClusterIP
  port: 3100

deployment:
  replicaCount: 1
  name: vrf-monitor
  imagePullSecrets: []
  env:
    REDIS_HOST: "10.0.135.50"
    REDIS_PORT: 6379
    NODE_ENV: production
    PORT: 3100
    BULL_WATCH_QUEUE_PREFIXES: bull
    UI: bull-board