## Klaytn Orakl Listener Configuration
## created by Bisonai

global:
  image:
    repository: docker.io/bisonai/orakl-api #repository url
    pullPolicy: IfNotPresent
    tag: "v0.0.2"  
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []

  config:
    DATABASE_URL:
    APP_PORT: 

  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value: ip-10-0-90-13.ap-southeast-1.compute.internal

  podAnnotations: {}

  livenessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5 

api:
  enabled: true
  replicas: 1
  serviceAccount:
    # -- Create a service account for the application controller
    create: true
    # -- Service account name
    name: orakl-api
    # -- Annotations applied to created service account
    annotations: {}
    # -- Automount API credentials for the Service Account
    automountServiceAccountToken: true

  podSecurityContext: {}

  containerSecurityContext: {}
  
  resources:
    # limits:
    #   cpu: 1500m
    #   memory: 6Gi
    # requests:
    #   cpu: 1500m
    #   memory: 6Gi

nodeSelector: {}
tolerations: []
dotenv: {}
