## Klaytn Orakl Api Configuration
## created by Bisonai
global:
  name: orakl-api
  namespace: orakl
  image:
    repository: public.ecr.aws/bisonai/orakl-api
    pullPolicy: IfNotPresent
    tag: "v0.0.1.20240502.0445.de5dadf"
    imagePullPolicy: IfNotPresent
    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository
    imagePullSecrets: []
  affinity:
    enabled: false
    key: kubernetes.io/hostname
    value:
  livenessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    path: /api/v1/
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
api:
  replicas: 1
  annotations: 
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'orakl'
    vault.hashicorp.com/agent-inject-template-config: |
      {{ with secret "baobab/data/api" -}}
        #!/bin/bash
        export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
      {{- end }}  
  podSecurityContext: {}
  containerSecurityContext: {}
  env:
    - name: VAULT_ADDR
      value: http://vault.vault.svc.cluster.local:8200/
    - name: JWT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: VAULT_ROLE
      value: orakl
    - name: VAULT_SECRET_PATH
      value: baobab
    - name: VAULT_KEY_NAME
      value: api
    - name: DATABASE_URL
      value: 
    - name: ENCRYPT_PASSWORD
      value: 
    - name: APP_PORT
      value: "3030"
    - name: REDIS_HOST
      value: redis-data-feed-master.redis.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
  resources:
    limits:
      cpu: 3000m
      memory: 5Gi
    requests:
      cpu: 3000m
      memory: 5Gi
nodeSelector: {}
tolerations: []
dotenv: {}
deployment:
  name: orakl-api
  replicas: 1
