name: CI Helm Lint

on:
  workflow_dispatch:
  push:
    branches:
      - i-56/feat/ci-helm-lint
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  #   paths:
  #     - '**/*.yaml'
  #     - '**/templates/*.tpl'
  #     - '**/templates/*.yaml'
  #     - '**/**/templates/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Helm lint
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            failed_services=""
            for file in $(git diff --name-only HEAD~1..HEAD); do
              dir=$(dirname $file)
              if [ -f "$dir/Chart.yaml" ]; then
                if ! helm lint $dir; then
                  exit 1
                fi
              fi
            done
