name: CI Helm Lint

on:
  workflow_dispatch:
  push:
    branches:
      - i-56/feat/ci-helm-lint
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  #   paths:
  #     - '**/*.yaml'
  #     - '**/templates/*.tpl'
  #     - '**/templates/*.yaml'
  #     - '**/**/templates/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Helm lint
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: find . -name 'Chart.yaml' -exec dirname {} \; | xargs -I {} helm lint {} | tee /dev/fd/2 | grep "\[ERROR\]" && exit 1 || exit 0
