name: CI Helm Lint

on:
  workflow_dispatch:
  push:
    branches:
      - i-56/feat/ci-helm-lint
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  #   paths:
  #     - '**/*.yaml'
  #     - '**/templates/*.tpl'
  #     - '**/templates/*.yaml'
  #     - '**/**/templates/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: List changed helm charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch i-56/feat/ci-helm-lint)
          echo $changed
          if [[ -n "$changed" ]]; then
            echo "true"
          fi

      - name: Run Helm lint to changed charts
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch i-56/feat/ci-helm-lint
